# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import login

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(415, 320)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.signupUi(MainWindow)
        self.loginUi(MainWindow)
        self.userUi(MainWindow)
        self.currentFrame = self.frame_signup
        self.frame_login.hide()
        self.frame_user.hide()

        MainWindow.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 415, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def signupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(415, 320)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.frame_signup = QtWidgets.QFrame(self.centralwidget)
        self.frame_signup.setGeometry(QtCore.QRect(10, 10, 397, 261))
        self.frame_signup.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_signup.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_signup.setObjectName("frame_signup")

        self.signupBtn = QtWidgets.QPushButton(self.frame_signup)
        self.signupBtn.setGeometry(QtCore.QRect(130, 200, 141, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.signupBtn.setFont(font)
        self.signupBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.signupBtn.setObjectName("signupBtn")

        self.qstnLogin = QtWidgets.QLabel(self.frame_signup)
        self.qstnLogin.setGeometry(QtCore.QRect(140, 220, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.qstnLogin.setFont(font)
        self.qstnLogin.setObjectName("qstnLogin")

        self.frame_signup2 = QtWidgets.QFrame(self.frame_signup)
        self.frame_signup2.setGeometry(QtCore.QRect(10, 60, 381, 131))
        self.frame_signup2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_signup2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_signup2.setObjectName("frame_signup2")
        self.fname_signup = QtWidgets.QLineEdit(self.frame_signup2)
        self.fname_signup.setGeometry(QtCore.QRect(10, 10, 171, 20))
        self.fname_signup.setObjectName("fname_signup")

        self.username_signup = QtWidgets.QLineEdit(self.frame_signup2)
        self.username_signup.setGeometry(QtCore.QRect(10, 40, 361, 19))
        self.username_signup.setObjectName("username_signup")

        self.lname_signup = QtWidgets.QLineEdit(self.frame_signup2)
        self.lname_signup.setGeometry(QtCore.QRect(190, 10, 181, 20))
        self.lname_signup.setObjectName("lname_signup")

        self.emailId_signup = QtWidgets.QLineEdit(self.frame_signup2)
        self.emailId_signup.setGeometry(QtCore.QRect(10, 70, 361, 19))
        self.emailId_signup.setObjectName("emailId_signup")

        self.password_signup = QtWidgets.QLineEdit(self.frame_signup2)
        self.password_signup.setGeometry(QtCore.QRect(10, 100, 361, 19))
        self.password_signup.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_signup.setObjectName("password_signup")

        self.label_signup = QtWidgets.QLabel(self.frame_signup)
        self.label_signup.setGeometry(QtCore.QRect(150, 20, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_signup.setFont(font)
        self.label_signup.setAlignment(QtCore.Qt.AlignCenter)
        self.label_signup.setObjectName("label_signup")

        self.redirectLogin = QtWidgets.QPushButton(self.frame_signup)
        self.redirectLogin.setGeometry(QtCore.QRect(160, 230, 75, 23))
        self.redirectLogin.setAutoFillBackground(False)
        self.redirectLogin.setStyleSheet("color:rgb(0, 85, 255)")
        self.redirectLogin.setFlat(True)
        self.redirectLogin.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.redirectLogin.setObjectName("redirectLogin")

        self.redirectLogin.clicked.connect(lambda: self.hide_change(self.frame_signup, self.frame_login))
        self.signupBtn.clicked.connect(lambda: self.signup(self.fname_signup.text(), self.lname_signup.text(), self.username_signup.text(), self.emailId_signup.text(), login.hashIt(self.password_signup.text())))

        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.fname_signup, self.lname_signup)
        MainWindow.setTabOrder(self.lname_signup, self.username_signup)
        MainWindow.setTabOrder(self.username_signup, self.emailId_signup)
        MainWindow.setTabOrder(self.emailId_signup, self.password_signup)
        MainWindow.setTabOrder(self.password_signup, self.signupBtn)
        MainWindow.setTabOrder(self.signupBtn, self.redirectLogin)

    def loginUi(self, MainWindow):
        self.frame_login = QtWidgets.QFrame(self.centralwidget)
        self.frame_login.setGeometry(QtCore.QRect(10, 10, 397, 261))
        self.frame_login.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_login.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_login.setObjectName("frame_login")

        self.loginBtn = QtWidgets.QPushButton(self.frame_login)
        self.loginBtn.setGeometry(QtCore.QRect(120, 140, 141, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.loginBtn.setFont(font)
        self.loginBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.loginBtn.setObjectName("loginBtn")

        self.qstnSignup = QtWidgets.QLabel(self.frame_login)
        self.qstnSignup.setGeometry(QtCore.QRect(130, 160, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.qstnSignup.setFont(font)
        self.qstnSignup.setAlignment(QtCore.Qt.AlignCenter)
        self.qstnSignup.setObjectName("qstnSignup")

        self.frame_login2 = QtWidgets.QFrame(self.frame_login)
        self.frame_login2.setGeometry(QtCore.QRect(10, 60, 381, 71))
        self.frame_login2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_login2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_login2.setObjectName("frame_login2")

        self.usernameEmailId_login = QtWidgets.QLineEdit(self.frame_login2)
        self.usernameEmailId_login.setGeometry(QtCore.QRect(10, 10, 361, 19))
        self.usernameEmailId_login.setText("")
        self.usernameEmailId_login.setObjectName("usernameEmailId_login")

        self.password_login = QtWidgets.QLineEdit(self.frame_login2)
        self.password_login.setGeometry(QtCore.QRect(10, 40, 361, 19))
        self.password_login.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_login.setObjectName("password_login")

        self.label_login = QtWidgets.QLabel(self.frame_login)
        self.label_login.setGeometry(QtCore.QRect(150, 20, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_login.setFont(font)
        self.label_login.setAlignment(QtCore.Qt.AlignCenter)
        self.label_login.setObjectName("label_login")

        self.redirectSignup = QtWidgets.QPushButton(self.frame_login)
        self.redirectSignup.setGeometry(QtCore.QRect(150, 170, 75, 23))
        self.redirectSignup.setAutoFillBackground(False)
        self.redirectSignup.setStyleSheet("color:rgb(0, 85, 255)")
        self.redirectSignup.setFlat(True)
        self.redirectSignup.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.redirectSignup.setObjectName("redirectSignup")

        self.redirectSignup.clicked.connect(lambda: self.hide_change(self.frame_login, self.frame_signup))
        self.loginBtn.clicked.connect(lambda: self.login(self.usernameEmailId_login.text(), login.hashIt(self.password_login.text())))

        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.usernameEmailId_login, self.password_login)
        MainWindow.setTabOrder(self.password_login, self.loginBtn)
        MainWindow.setTabOrder(self.loginBtn, self.redirectSignup)

    def userUi(self, MainWindow):
        self.frame_user = QtWidgets.QFrame(self.centralwidget)
        self.frame_user.setGeometry(QtCore.QRect(60, 10, 301, 261))
        self.frame_user.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_user.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_user.setObjectName("frame_user")

        self.changePassword = QtWidgets.QPushButton(self.frame_user)
        self.changePassword.setGeometry(QtCore.QRect(100, 220, 101, 21))
        self.changePassword.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.changePassword.setStyleSheet("color:rgb(0, 85, 255)")
        self.changePassword.setFlat(True)
        self.changePassword.setEnabled(False)
        self.changePassword.setObjectName("changePassword")

        self.nameLabel = QtWidgets.QLabel(self.frame_user)
        self.nameLabel.setGeometry(QtCore.QRect(10, 60, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Orbitron Medium")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.nameLabel.setFont(font)
        self.nameLabel.setTextFormat(QtCore.Qt.AutoText)
        self.nameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.nameLabel.setObjectName("nameLabel")

        self.editBtn = QtWidgets.QPushButton(self.frame_user)
        self.editBtn.setEnabled(False)
        self.editBtn.setGeometry(QtCore.QRect(220, 60, 51, 23))
        self.editBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.editBtn.setStyleSheet("background-color:rgb(202, 202, 202)")
        self.editBtn.setObjectName("editBtn")

        self.emailIdLabel = QtWidgets.QLabel(self.frame_user)
        self.emailIdLabel.setGeometry(QtCore.QRect(130, 110, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Orbitron Medium")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.emailIdLabel.setFont(font)
        self.emailIdLabel.setTextFormat(QtCore.Qt.AutoText)
        self.emailIdLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.emailIdLabel.setObjectName("emailIdLabel")

        self.nameDisplayLabel = QtWidgets.QLabel(self.frame_user)
        self.nameDisplayLabel.setGeometry(QtCore.QRect(10, 80, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Orbitron")
        font.setPointSize(8)
        font.setWeight(50)
        self.nameDisplayLabel.setFont(font)
        self.nameDisplayLabel.setText("")
        self.nameDisplayLabel.setObjectName("nameDisplayLabel")

        self.passwordLineEdit = QtWidgets.QLineEdit(self.frame_user)
        self.passwordLineEdit.setGeometry(QtCore.QRect(10, 220, 91, 20))
        self.passwordLineEdit.setFrame(False)
        self.passwordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordLineEdit.setReadOnly(True)
        self.passwordLineEdit.setObjectName("passwordLineEdit")

        self.emailIdDisplayLabel = QtWidgets.QLabel(self.frame_user)
        self.emailIdDisplayLabel.setGeometry(QtCore.QRect(130, 130, 131, 16))
        font = QtGui.QFont()
        font.setFamily("Orbitron")
        font.setPointSize(8)
        font.setWeight(50)
        self.emailIdDisplayLabel.setFont(font)
        self.emailIdDisplayLabel.setText("")
        self.emailIdDisplayLabel.setObjectName("emailIdDisplayLabel")

        self.usernameLabel = QtWidgets.QLabel(self.frame_user)
        self.usernameLabel.setGeometry(QtCore.QRect(10, 110, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Orbitron Medium")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.usernameLabel.setFont(font)
        self.usernameLabel.setTextFormat(QtCore.Qt.AutoText)
        self.usernameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.usernameLabel.setObjectName("usernameLabel")

        self.usernameDisplayLabel = QtWidgets.QLabel(self.frame_user)
        self.usernameDisplayLabel.setGeometry(QtCore.QRect(10, 130, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Orbitron")
        font.setPointSize(8)
        font.setWeight(50)
        self.usernameDisplayLabel.setFont(font)
        self.usernameDisplayLabel.setText("")
        self.usernameDisplayLabel.setObjectName("usernameDisplayLabel")

        self.passwordLabel = QtWidgets.QLabel(self.frame_user)
        self.passwordLabel.setGeometry(QtCore.QRect(10, 200, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Orbitron Medium")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.passwordLabel.setFont(font)
        self.passwordLabel.setTextFormat(QtCore.Qt.AutoText)
        self.passwordLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.passwordLabel.setObjectName("passwordLabel")

        self.userDetailsLabel = QtWidgets.QLabel(self.frame_user)
        self.userDetailsLabel.setGeometry(QtCore.QRect(30, 10, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Simplified Arabic Fixed")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.userDetailsLabel.setFont(font)
        self.userDetailsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.userDetailsLabel.setObjectName("userDetailsLabel")

        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 415, 21))
        self.menubar.setObjectName("menubar")

        self.menuLogout = QtWidgets.QMenu(self.menubar)
        self.menuLogout.setEnabled(False)
        self.menuLogout.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.menuLogout.setObjectName("menuLogout")

        MainWindow.setMenuBar(self.menubar)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.signupBtn.setText(_translate("MainWindow", "SignUp"))
        self.signupBtn.setShortcut(_translate("MainWindow", "Return"))
        self.qstnLogin.setText(_translate("MainWindow", "Already have an account?"))
        self.fname_signup.setPlaceholderText(_translate("MainWindow", "First Name"))
        self.username_signup.setPlaceholderText(_translate("MainWindow", "Username"))
        self.lname_signup.setPlaceholderText(_translate("MainWindow", "Last Name"))
        self.emailId_signup.setPlaceholderText(_translate("MainWindow", "Email ID"))
        self.password_signup.setPlaceholderText(_translate("MainWindow", "Password"))
        self.label_signup.setText(_translate("MainWindow", "SignUp"))
        self.redirectLogin.setText(_translate("MainWindow", "Login"))
        self.loginBtn.setText(_translate("MainWindow", "Login"))
        self.loginBtn.setShortcut(_translate("MainWindow", "Return"))
        self.qstnSignup.setText(_translate("MainWindow", "Don\'t have an account?"))
        self.usernameEmailId_login.setPlaceholderText(_translate("MainWindow", "Username / Email ID"))
        self.password_login.setPlaceholderText(_translate("MainWindow", "Password"))
        self.label_login.setText(_translate("MainWindow", "Login"))
        self.redirectSignup.setText(_translate("MainWindow", "Register"))
        self.changePassword.setText(_translate("MainWindow", "Change Password"))
        self.nameLabel.setText(_translate("MainWindow", "NAME"))
        self.editBtn.setText(_translate("MainWindow", "Edit"))
        self.emailIdLabel.setText(_translate("MainWindow", "EMAIL ID"))
        self.passwordLineEdit.setText(_translate("MainWindow", "password"))
        self.usernameLabel.setText(_translate("MainWindow", "USERNAME"))
        self.passwordLabel.setText(_translate("MainWindow", "PASSWORD"))
        self.userDetailsLabel.setText(_translate("MainWindow", "User Details"))
        self.menuLogout.setTitle(_translate("MainWindow", "Logout"))

    def hide_change(self, toHide, toShow):
        toHide.hide()
        toShow.show()
        self.currentFrame = toShow

    def signup(self, fname, lname, username, email_id, password):
        if '' in [self.fname_signup.text(), self.lname_signup.text(), self.username_signup.text(), self.emailId_signup.text(), self.password_signup.text()]:
            signupErrorMsg = QMessageBox()
            signupErrorMsg.setWindowTitle("SignUp Error!")
            signupErrorMsg.setText("Do not leave any field. Enter valid information")
            signupErrorMsg.setIcon(QMessageBox.Critical)

            x = signupErrorMsg.exec_()
        else:    
            notValidItem ,validSignup = login.signup(fname, lname, username, email_id, password)
            if validSignup:
                self.hide_change(self.currentFrame, self.frame_login)

                self.fname_signup.clear()
                self.lname_signup.clear()
                self.username_signup.clear()
                self.emailId_signup.clear()
                self.password_signup.clear()
            else:
                invalidSignupMsg = QMessageBox()
                invalidSignupMsg.setWindowTitle("Invalid SignUp")
                invalidSignupMsg.setText(f"{notValidItem} already exists")
                invalidSignupMsg.setIcon(QMessageBox.Warning)

                x = invalidSignupMsg.exec_()

    def login(self, usernameEmailId, password):
        # print(self.usernameEmailId_login.text().__repr__(), self.password_login.text().__repr__())
        if self.usernameEmailId_login.text() == '' or self.password_login.text() == '':
            loginErrorMsg = QMessageBox()
            loginErrorMsg.setWindowTitle("Login Error!")
            if self.usernameEmailId_login.text() == '' and self.password_login.text() != '':
                loginErrorMsg.setText("Enter a Username/Email ID")
                loginErrorMsg.setIcon(QMessageBox.Critical)
            elif self.password_login.text() == '' and self.usernameEmailId_login.text() != '':
                loginErrorMsg.setText("Enter a Password")
                loginErrorMsg.setIcon(QMessageBox.Critical)
            else:
                loginErrorMsg.setText("Enter Username/Email ID and Password")
                loginErrorMsg.setIcon(QMessageBox.Critical)

            x = loginErrorMsg.exec_()
        else:
            self.username, self.loggedIn = login.login(usernameEmailId, password)
            if self.loggedIn:
                self.fname, self.lname, self.username, self.email_id = login.returnUserDetails(self.username)

                loggedInMsg = QMessageBox()
                loggedInMsg.setWindowTitle("Logged In")
                loggedInMsg.setText("You have been Successfully Logged In")
                loggedInMsg.setIcon(QMessageBox.Information)

                x = loggedInMsg.exec_()

                self.displayUser(self.fname, self.lname, self.username, self.email_id)
                self.hide_change(self.currentFrame, self.frame_user)
                self.usernameEmailId_login.clear()
                self.password_login.clear()
            else:
                invalidLoginMsg = QMessageBox()
                invalidLoginMsg.setWindowTitle("Invalid Login!")
                invalidLoginMsg.setText("Incorrect Password/Username/Email ID. Please Try Again!")
                invalidLoginMsg.setIcon(QMessageBox.Critical)

                x = invalidLoginMsg.exec_()


    def displayUser(self, fname, lname, username, email_id):
        self.nameDisplayLabel.setText(f"{fname} {lname}")
        self.nameDisplayLabel.adjustSize()
        self.usernameDisplayLabel.setText(f"{username}")
        self.usernameDisplayLabel.adjustSize()
        self.emailIdDisplayLabel.setText(f"{email_id}")
        self.emailIdDisplayLabel.adjustSize()
        self.hide_change(self.currentFrame, self.frame_user)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

# ~sr